name: Deploy

on:
  push:
    branches: [ 'main' ]

env:
  TEST_TAG: noldor/api-docs:test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        tags: ${{ env.TEST_TAG }}
        push: false

    - name: Start Docker container and build web pages
      run: docker run --rm -v ${{ github.workspace }}/build:/srv/slate/build ${{ env.TEST_TAG }} build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true
